nestjs/typeorm

lib/index.ts
=> fix(@nestjs/typeorm) expose the getRepositoryToken method

lib/typeorm-core.module.ts, lib/typeorm.decorators.ts, lib/typeorm.module.ts, lib/typeorm.providers.ts, lib/typeorm.utils.ts, package.json
For the needs of one of my projects, I have to handle connections to different databases. This was not possible with the `nestjs/typeorm` module : 
- The `TypeOrmModule.forRoot` function only takes one connection options object, thus only creates one connection to one database
- The `Connection` created by the `TypeOrmModule.forRoot({... connection options ...})` would get `Connection` as an injection token, no matter what. This means that multiple calls to `forRoot` wasn't a solution
This PR adds the support for multiple connections and there is no breaking change ;)
There is a usage example:
```js
@Module({
imports: [
TypeOrmModule.forRoot({
type: 'postgres',
name: 'animalsConnection', // pay attention to the connection name
host:  'database_host_01',
port: 5432,
username: 'user', …
```
=> feat(@nestjs/typeorm) add multiple connections support

README.md
the typeorm link didnt work since it was missing the `http://` prefix and instead redirected you to an 404 page.
=> added `http://` to make link to `typeorm.io` work.

lib/typeorm.providers.ts
http://typeorm.io/#/custom-repository
Currently type orm fails as it tries to load custom repository as an Entity.
> No repository for "UserRepository" was found. Looks like this entity is not registered in current "default" connection?
We should check if "entity" is extending `Repository`, if it is, then we know this is custom repository and load it `getCustomRepository`. 
This way we can do:
```ts
...
imports: [
// User is entity, UserRepository is custom repository
TypeOrmModule.forFeature([User, UserRepository]), 
]
...
```
About mongo support. I'm not sure if it supports custom repositories at all. I can't find anything in the documentation.
EDIT: Mongo supports custom repositories as well. No changes needed.
=> Add support for custom repositories

lib/typeorm.utils.ts
Currently the same error message is displayed regardless of the underlying
cause of failure . This change also outputs the Error.stack string to the
logger.
Fixes #30
- [x ] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
(no tests in this project)
(no specific docs in this project
```
[ ] Bugfix
[x ] Feature
```
When attempting to connect using the `handleRetry` operator, all error information from TypeORM is swallowed and a generic "Unable to …
=> feature: log TypeORM error stack when connection fails

lib/common/typeorm.utils.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: [#55](https://github.com/nestjs/typeorm/issues/55)
`getRpositoryToken(UserRepository)` now returns `'UserRepository'` instead of `'UserRepositoryRepository'`.
`getRpositoryToken(User)` still returns `'UserRepository'`.
A new utility function was created to generate injection tokens specifically for custom repositories.
```
getCustomRepositoryToken(repository: Function): string
```
```
[x] Yes
[ ] No
```
If you are using a [TypeORM Custom Repository](http://typeorm.io/#/custom-repository) and are relying on the `@InjectRepository()` decorator to inject your …
=> getRepositoryToken returns correct tokens for custom repositories

lib/interfaces/typeorm-options.interface.ts, lib/typeorm-core.module.ts
Pass connection name to the options factory, so different options can be
returned for different connections.
```
[ ] Bugfix
[x] Feature
```
Currently TypeOrmModule can use options factory to retrieve connection options, for example, from some configuration service, but no arguments are passed to `createTypeOrmOptions()` medhod, so this feature is unused in a case of multiple database connections.
optional `name` parameter is passed to the options factory, so developers can use it for …
=> feature: options factory for multiple connections

lib/common/typeorm.utils.ts, lib/typeorm-core.module.ts
Add more type casting inside onModuleDestroy to prevent it from
complaining about type mismatch
=> fix(TypeOrmCoreModule): add more Type casting to onModuleDestroy

lib/common/typeorm.decorators.ts, lib/common/typeorm.utils.ts, lib/typeorm.providers.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #68
Add an optional second parameter on `@InjectRepository` to specify the server name. Default connection name will be `default` if not provide.
```ts
@InjectRepository(User, 'custom_server_name') private readonly user: Repository<User>
@InjectRepository(UserRepository, 'custom_server_name') private readonly userRepository: UserRepository
```
**NOTE:** Another slightly changes, if you are define a connection name eg: `my_server` in your module, then when …
=> support @InjectRepository with multi connection

package.json
- [ X] Tests for the changes have been added (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[X] Build related changes
```
when I update nest  project, there was an error occur: 
```
$ npm update
> @nestjs/core@6.2.0 postinstall /Users/development/nest-quick-start/node_modules/@nestjs/core
> opencollective || exit 0
Thanks for installing nest 🙏
Please consider donating to our open collective
to help us maintain this package.
Number of contributors: 79
Number of backers: 169
Annual budget: US$ 63,283
Current balance: US$ …
```
=> update dependencies "reflect-metadata"  from `0.1.12` to `^0.1.12`.

CONTRIBUTING.md
Message format requires colon between type and subject.
My commit failed when I omitted the colon. I do see some commits on other nest projects that do not have the colon. Not sure exactly what the rule is supposed to be.
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Documentation
```
```
[ ] Yes
[X] No
```
=> docs(contributing): fix commit message examples

lib/common/typeorm.utils.ts, lib/typeorm-core.module.ts
Enable easier debugging when using multiple named connections.
Resolves #484
```
[ ] Bugfix
[X] Feature
```
Issue Number: #484
Retry connection log message displays connection name.
```
[ ] Yes
[X] No
```
=> feat(@nestjs/typeorm): add connection name to retry message

lib/common/typeorm.decorators.ts, lib/common/typeorm.utils.ts, lib/entities-metadata.storage.ts, lib/interfaces/entity-class-or-schema.type.ts, lib/typeorm.module.ts, lib/typeorm.providers.ts, tests/e2e/typeorm-schema.spec.ts, tests/src/app-schema.module.ts, tests/src/database.module.ts, tests/src/photo/schema/photo-schema.controller.ts, tests/src/photo/schema/photo-schema.module.ts, tests/src/photo/schema/photo-schema.repository.ts, tests/src/photo/schema/photo-schema.service.ts, tests/src/photo/schema/photo-without-target.schema.ts, tests/src/photo/schema/photo.schema.ts
closes nestjs/typeorm#151
```
[ ] Bugfix
[x] Feature
```
Now it is not possible to use EntitySchema with Nestjs/TypeOrm without using ts-ignore and casting as an any. 
Issue Number: #151
Module correctly resolves EntitySchema as a valid Entity, creates providers for that entity. We can use EntitySchema instance with the InjectRepository decorator.
```
[ ] Yes
[x] No
```
=> feat(): add support for entity schema

lib/typeorm.custom.repository.ts, lib/typeorm.module.ts
Now if you want to use custom repository, you must have to add entity to TypeOrmModule.forFeature method, otherwise No metadata for {entity} was found error  will happen.
=> Using custom repository, not need to add entity to TypeOrmModule.forFeature

lib/typeorm-core.module.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
(node:31429) UnhandledPromiseRejectionWarning: CannotExecuteNotConnectedError: Cannot execute operation on "default" connection because connection is not yet established.
at new CannotExecuteNotConnectedError (/Users/zhaofeng/workspace/yr/yanrong.tech/src/error/CannotExecuteNotConnectedError.ts:8:9)
at Connection.<anonymous> (/Users/zhaofeng/workspace/yr/yanrong.tech/src/connection/Connection.ts:226:19)
at step …
```
=> fix(): stop app with unexpected error when the connection is not ready

lib/common/typeorm.utils.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
N/A
```
[ ] Yes
[x] No
```
This PR, It replaces the`isNullOrUndefined` method as it is deprecated, following the following warning message:
`deprecated  - use value === null || value === not defined`
=> chore(typeorm-utils): improvement

tsconfig.json
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
When using this package, we don't get any of those useful comments on typescript interfaces because they were dropped due to `removeComments` flag
```
[ ] Yes
[x] No
```
=> build: do not remove comments

lib/typeorm-core.module.ts
If a NestJS app destroys a `dataSource` instance before app shutdown, they will see the following error:
```
Cannot execute operation on "default" connection because connection is not yet established.
```
A NestJS app can destroy a `dataSource` instance before app shutdown and they will not see the following error logged:
```
Cannot execute operation on "default" connection because connection is not yet established.
```
=> Check if datasource is initialized before destroying it

lib/interfaces/typeorm-options.interface.ts, lib/typeorm-core.module.ts
It may be a bug fix or a feature, I'm not sure how you consider this PR
Today, when calling the `forRootAsync` function, it is not possible to define your own providers if necessary
Here is an example in one of my projects where I want to encapsulate the declaration of the `TypeOrmModule` module in my own `DatabaseModule` module so as not to repeat the declaration of my logger or other common options several times. This module is at the root of my Git repository and is used in different NestJS applications that I have in this same Git repository
- `database.module.ts`
```ts
export type DatabaseModuleOptions = TypeOrmModuleOptions
export type DatabaseModuleAsyncOptions …
```
=> feat: allow adding providers when the module is loaded asynchronously

lib/typeorm-core.module.ts
Initialising datasource in dataSourceFactory throw an exceprtion 
But docs says that it is correct usage 
```ts
TypeOrmModule.forRootAsync({
imports: [ConfigModule],
inject: [ConfigService],
// Use useFactory, useClass, or useExisting
// to configure the DataSourceOptions.
useFactory: (configService: ConfigService) => ({
type: 'mysql',
host: configService.get('HOST'),
port: +configService.get('PORT'),
username: configService.get('USERNAME'),
password: configService.get('PASSWORD'),
database: configService.get('DATABASE'),
entities: [],
synchronize: true,
}),
// dataSource receives the configured DataSourceOptions
// and returns a Promise<DataSource>.
dataSourceFactory: async (options) …
```
=> Do not initialize datasource if already initialized

lib/typeorm.providers.ts
check if the entity has tree metadata and return a tree repository if it exists
Currently the providers don't return a TreeRepository for tree entities.
Now the provider will create and return a tree repository for tree entities
=> fix(provider): return proper repository

lib/interfaces/typeorm-options.interface.ts, lib/typeorm-core.module.ts
Motivation for no tests:
I searched repository for proper place to add tests for this feature but none seem to be correct (there are only e2e tests with specific convention).
I run e2e suite though and it passes.
I also tested the feature manually on my usecase (on and off).
Please suggest test convention if you want me to write tests for this feature and I will do my best to apply it.
There is no option to disable `DataSource` initialization during module initialization
Issue Number: 1762
Option `manualInitialization` was added to `TypeOrmModuleOptions` interface.
Module does not initialize database if option is set to `true`.
I have done one minor refactor to limit logic repetition
=> feat(): add support for manual init

lib/common/typeorm.utils.ts, lib/typeorm-core.module.ts, lib/typeorm.providers.ts, package-lock.json, package.json
The `crypto` global is available in all supported Node.js versions as well as [in all major browsers](https://caniuse.com/mdn-api_crypto_randomuuid). The uuid module is rendered unnecessary for uuidv4.
`@nestjs/graphql` is currently downloaded about 580000 times per week, so about 30740000 times per year. `uuid@11` is about 3.7 kB in size (gzipped+minified). Removing this dependency saves about 113GB traffic per year.
=> chore(deps): Use `crypto.randomUUID()` instead of `uuid` module
